# Generated by Django 6.0 on 2026-01-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
